version: '3.12'

services:
  xdr_app:
    build: .
    container_name: xdr_agent
    command: poetry run python app/main.py
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=production
