[tool.poetry]
name = "forge-xdr-agent"
version = "0.1.0"
description = ""
authors = ["Constantin Hentgen <constantin.hentgen@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
